name: Deploy to Render

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and Deploy Strapi
        run: |
          curl -X POST -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
          -d '{"serviceId": "your-strapi-service-id"}' \
          https://api.render.com/deploy

      - name: Build and Deploy Express
        run: |
          curl -X POST -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
          -d '{"serviceId": "your-express-service-id"}' \
          https://api.render.com/deploy
